"""Modal batch generation for the baseline and SFT instances.

Generates ``samples_per_prompt`` responses per evaluation prompt for every
instance and appends them to data/eval_generations_v2.json. Adapter-merged
instances are generated by modal_merge_adapters.py.

Usage:
    modal run modal_evaluate.py --instance all
    modal run modal_evaluate.py --instance baseline
    modal run modal_evaluate.py --instance sft_left_s42,sft_right_s42
    modal run modal_evaluate.py --instance sft --limit-prompts 10   # dry run
"""

import modal

app = modal.App("preference-collapse-eval")

image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("torch", "transformers", "peft", "bitsandbytes", "accelerate")
    .env({"HF_HOME": "/hf-cache", "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True"})
    .add_local_python_source("src")
)

models_vol = modal.Volume.from_name("preference-collapse-models")
hf_cache_vol = modal.Volume.from_name("preference-collapse-hf-cache")


@app.function(
    gpu="L40S",
    image=image,
    volumes={"/models": models_vol, "/hf-cache": hf_cache_vol},
    secrets=[modal.Secret.from_name("huggingface-secret", required_keys=["HF_TOKEN"])],
    timeout=2 * 3600,
)
def generate_for_instance(instance: dict, prompts: list[dict], gen_cfg: dict) -> list[dict]:
    """Generate all samples for one baseline/SFT instance."""
    from src.generation import generate_samples, load_instance_model

    from src.generation import persist_rows_on_volume

    print(f"Loading instance {instance['instance']} ({instance['kind']})")
    model, tokenizer = load_instance_model(instance)
    print(f"Generating {len(prompts)} prompts x {gen_cfg['samples_per_prompt']} samples")
    rows = generate_samples(model, tokenizer, prompts, instance, **gen_cfg)
    persist_rows_on_volume(rows, instance, models_vol)
    return rows


@app.local_entrypoint()
def main(
    instance: str = "all",
    output_file: str = "data/eval_generations_v2.json",
    config: str = "configs/config.yaml",
    limit_prompts: int = 0,
):
    """Generate evaluation responses for baseline and SFT instances."""
    import sys
    sys.path.insert(0, ".")
    import yaml
    from src.eval_prompts import get_all_eval_prompts
    from src.generation import (
        GEN_DEFAULTS, build_instances, load_records, missing_prompts,
        save_records, select_instances,
    )

    cfg = yaml.safe_load(open(config))
    gen_cfg = {**GEN_DEFAULTS, **cfg.get("generation", {})}
    seeds = cfg["training"]["seeds"]
    control_pairs = [tuple(p) for p in cfg.get("merging", {}).get("control_pairs", [])]

    prompts = get_all_eval_prompts(n_per_origin=cfg["datasets"]["n_eval_split_per_origin"])
    if limit_prompts:
        prompts = prompts[:limit_prompts]
    instances = [i for i in build_instances(seeds, control_pairs) if i["kind"] in ("baseline", "sft")]
    instances = select_instances(instances, instance)

    rows = load_records(output_file)
    print(f"Loaded {len(rows)} existing records from {output_file}")

    jobs = []
    for inst in instances:
        needed = missing_prompts(rows, inst, prompts, gen_cfg["samples_per_prompt"])
        if not needed:
            print(f"Skipping {inst['instance']} — complete")
            continue
        print(f"Queued {inst['instance']}: {len(needed)} prompts")
        jobs.append((inst, needed, gen_cfg))

    # Instances run in parallel on separate GPUs; results are saved as they arrive.
    for new_rows in generate_for_instance.starmap(jobs, order_outputs=False):
        rows.extend(new_rows)
        save_records(output_file, rows)
        print(f"Saved {len(rows)} total records to {output_file} "
              f"(+{len(new_rows)} from {new_rows[0]['instance'] if new_rows else '?'})")

    print(f"\nDone. {len(rows)} records in {output_file}")
